version: '3'

services:

  broker_0:
    image: wurstmeister/kafka:2.11-2.0.0
    networks:
       - cluster_net 
       - zk_cluster_net
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.138.110:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181/kafka

  broker_1:
    image: wurstmeister/kafka:2.11-2.0.0
    networks:
        - cluster_net 
        - zk_cluster_net
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.138.110:9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181/kafka

  broker_2:
    image: wurstmeister/kafka:2.11-2.0.0
    networks:
        - cluster_net 
        - zk_cluster_net
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.138.110:9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181/kafka

networks:
  cluster_net:
  zk_cluster_net:
    external:
      name: zookeeper_cluster_net
